### PR TITLE
feat: introducing scout tracking and updated post author tracking

### PR DESCRIPTION
**Pull request by rebelchris**
### Describe what this PR does
- We didn't include post author in every graphQL query
- Added new `post_scout_id` parameter
- Fixed some scout elements on the comments

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-144 #done

### CODE REVIEW

**Comment by rebelchris** [comment]
@idoshamun Tagged you from a analytics perspective only :)

**Review by kirillkurko — APPROVED** [review]
Looks good, but what I see outside of this task is that that MainComment and SubComment components are really similar, so maybe we can create a task to implement kinda general comment component that can be used for replacing both mentioned component

**Comment by rebelchris** [comment]
@sshanzel We where missing the id from the author query, so you see that field being added.
Also one new refactor in the companion boot data to simply include `author` and `scout` completly.

@kirillkurko Great idea, I'll add it to the backlog :)

**Comment by sshanzel** [comment]
@rebelchris ah, saw it now! Thank you! Think I'm going blind 😆

**Pull request merged**
