### PR TITLE
fix: improve upvote/downvote design

### PR DESCRIPTION
**Pull request by nensidosari**
### Describe what this PR does
- Moved number of upvotes inside upvotes button
- Added a separator div between downvote and upvote

Screenshot 2024-01-23 at 12 40 24 AM
Screenshot 2024-01-23 at 12 40 16 AM
Screenshot 2024-01-23 at 12 40 11 AM
Screenshot 2024-01-23 at 12 40 02 AM
Screenshot 2024-01-23 at 12 39 43 AM
Screenshot 2024-01-23 at 12 39 28 AM
Screenshot 2024-01-23 at 12 39 17 AM
Screenshot 2024-01-23 at 12 39 24 AM

### On those affected packages:
- [x] Have you done sanity checks in the webapp?
- [x] Have you done sanity checks in the extension?
- [x] Does this not break anything in companion?

### Did you test the modified components media queries?
- [x] MobileL (420px)
- [x] Tablet (656px)
- [x] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

MI-99 #done

### CODE REVIEW

**Comment by sshanzel** [comment]
Where can we find the Figma file for the changes proposed here?

**Review by sshanzel — APPROVED** [review]
Looks great nonetheless! 🚀

**Comment by nensidosari** [comment]
> Where can we find the Figma file for the changes proposed here?

@sshanzel apologies for not attaching it - [Figma](https://www.figma.com/file/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?type=design&node-id=275-12169&mode=design&t=rx7r4aMAvvFFrHaZ-0) file

**Comment by sshanzel** [comment]
> > Where can we find the Figma file for the changes proposed here?
> 
> @sshanzel apologies for not attaching it - [Figma](https://www.figma.com/file/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?type=design&node-id=275-12169&mode=design&t=rx7r4aMAvvFFrHaZ-0) file

Hey, all cool. I just thought I was looking at the wrong thing. But yes, everything looked great 🚀

**Pull request merged**
