### PR TITLE
fix: prevent default event handling when opening context menu

### PR DESCRIPTION
**Pull request by DragosIorgulescu**
## Changes

- this is already applied in most places, was not being handled on the squad members modal users list

https://github.com/dailydotdev/apps/assets/1225100/ef2aa2c0-1a6e-42f8-b9cb-7ecab3ae9f03

## Events

N / A

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [x] MobileL (420px)
- [x] Tablet (656px)
- [x] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

MI-260 #done

### CODE REVIEW

**Review by sshanzel — APPROVED** [review]
LGTM! 🚀

**Comment by sshanzel** [comment]
Would it be not possible to handle this generally? Like the component we use for the list?

**Comment by DragosIorgulescu** [comment]
> Would it be not possible to handle this generally? Like the component we use for the list?

We can apply it generally [here](https://github.com/dailydotdev/apps/blob/a8c0039bf5a807eaa5ede1fecce42b3b9f8e01f0/packages/shared/src/hooks/useContextMenu.ts#L44-L60) but I'm hesitant to do that as I am not sure if would break or mess up with anything wherever this is used. 

When I initially refactored this I did try to go through all menus and make sure this is handled wherever it is needed, but I must have missed this one.

**Comment by sshanzel** [comment]
> @sshanzel good point, we can apply it generally [here](https://github.com/dailydotdev/apps/blob/a8c0039bf5a807eaa5ede1fecce42b3b9f8e01f0/packages/shared/src/hooks/useContextMenu.ts#L44-L60) but I'm hesitant to do that as I am not sure if would break or mess up with anything wherever this is used.

Yeah, if ever we decide to change it there, we will fix all the other cases. Up to you, we can merge or if you want to make changes.

**Review by rebelchris — APPROVED** [review]

**Pull request merged**
