### PR TITLE
fix: squad post image in feed

### PR DESCRIPTION
**Pull request by sshanzel**
## Changes
- Fix squad post image in feed for the experiment.

## Events

Did you introduce any new tracking events?

## Experiment

Did you introduce any new experiments?

## Manual Testing

> [!CAUTION]
> Please make sure existing components are not breaking/affected by this PR

### Preview domain
https://fix-author-image.preview.app.daily.dev

### CODE REVIEW

**Comment by sshanzel** [comment]
Before:

Screenshot 2024-07-22 at 5 15 36 PM

After:

Screenshot 2024-07-22 at 5 15 15 PM

**Comment by nensidosari** [comment]
Screenshot 2024-07-22 at 2 09 36 PM

PR looks great, just one thing on the control variation, the author image appears now behind the squad image. Let's fix that and we can merge 🙏

**Comment by sshanzel** [comment]
Looks normal to me. Can you refresh and check here?

https://app.daily.dev/squads/db9d9c61-7296-4ef0-9d4d-62dc93b197fa

Screenshot 2024-07-22 at 8 23 55 PM
Screenshot 2024-07-22 at 8 24 07 PM

**Comment by nensidosari** [comment]
@sshanzel u're checking in the wrong domain - please check here https://fix-author-image.preview.app.daily.dev/squads/db9d9c61-7296-4ef0-9d4d-62dc93b197fa

**Comment by sshanzel** [comment]
> @sshanzel u're checking in the wrong domain - please check here https://fix-author-image.preview.app.daily.dev/squads/db9d9c61-7296-4ef0-9d4d-62dc93b197fa

Rookie mistakes 🤦 

Can, you check again now?

**Review by nensidosari — APPROVED** [review]

**Pull request merged**
