### PR TITLE
fix: disabling links while response is still streaming

### PR DESCRIPTION
**Pull request by sshanzel**
## Changes
- While streaming the data, we update the link to `#` so even while the link is still incomplete, it won't be redirected to any wrong url.

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-1734 #done

### CODE REVIEW

**Review by rebelchris — COMMENTED** [review]
Is there no way we can make links clickable and working during streaming?
Not sure it's supported
Or show them as "disabled"

It's the same for the copy code button, they just don't work,. ideally they do.

**Comment by rebelchris** [comment]
Hmm that's annoying, also for the copy codeblocks?
I tested it where it already streamed beyond the first block so expected it to work

**Review by capJavert — COMMENTED** [review]
From what I see the links are clickable as soon as their markdown block is rendered.. only way when they are wrong its when markdown is not complete eg. `[This is link](https://something` (so the closing bracket is missing) but I would expect users understanding that this is not clickable. So links are clickable always from what I see.

As for code I think it might be due to parent div being updated constantly and events not bubbling because react is busy rendering vs propagating events. Just main thread being busy.

**Comment by sshanzel** [comment]
The only concern is then, we currently don't have a way for us to identify whether the link is now rendered complete. If there is any, feel free to shoot.

**Review by DragosIorgulescu — APPROVED** [review]
Looks good 👌 as a quick fix solution. Regarding the points raised above, it might be worth exploring using web workers for this

**Review by rebelchris — APPROVED** [review]

**Pull request merged**
