### PR TITLE
feat: expose staff members in comments

### PR DESCRIPTION
**Pull request by rebelchris**
## Changes

Badge for Staff members :)

Still awaiting design team response and hoping they can deliver us a cooler emoji.

Screenshot 2024-07-04 at 19 58 16

## Events

Did you introduce any new tracking events?

## Experiment

Did you introduce any new experiments?

## Manual Testing

> [!CAUTION]
> Please make sure existing components are not breaking/affected by this PR

### Preview domain
https://feat-expose-staff.preview.app.daily.dev

### CODE REVIEW

**Review by sshanzel — APPROVED** [review]
Now that looks amazing 😎

**Review by omBratteng — APPROVED** [review]
wololo

Yeah, a different icon would work better I think. Especially since this has a background that fills the entire icon, making the spacing between it and the text much more narrower.
Plus, the logo is visually a bit off center I 😬

**Review by nensidosari — APPROVED** [review]
Nicee

**Comment by rebelchris** [comment]
@omBratteng Yeah more of a temporary placeholder.
Tomer wants to make some changes to this render part actually so will just wait as it's not really a product thing.

**Pull request closed without merging**
