### PR TITLE
fix: profile picture vertical line

### PR DESCRIPTION
**Pull request by el**
## Changes

before: (changed the line color temporarily to make it seen on preview)
SCR-20230131-g3g
after:
SCR-20230131-g4b

### Describe what this PR does
- Short and concise, bullet points can help
- Screenshots if applicable can also help

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-{number} #done

### CODE REVIEW

**Review by idoshamun — APPROVED** [review]
Awesome!

**Comment by sshanzel** [comment]
I believe this was fixed already from this commit https://github.com/dailydotdev/apps/commit/c7466b148a6603f33ffc26ae18344888db690abb

**Comment by rebelchris** [comment]
@sshanzel i do think this will work, without passing classnames :) maybe refactor the other one.

Also be sure to both assign tickets and look at jira 🙏

**Comment by sshanzel** [comment]
@rebelchris if there will be any additional padding/margin to the container where the current `z-index` is applied here, there will be a gap between the avatar and the timeline itself.

**Pull request merged**
