### PR TITLE
fix: fix flagged version of login button

### PR DESCRIPTION
**Pull request by rebelchris**
Added the login button flagged version to be uniform.

Do note for the mobile sidebar version it will always render "Login" but at least this makes everything loaded from 1 component now.

DD-390 #done

### CODE REVIEW

**Review by sshanzel — APPROVED** [review]
🚢

**Review by idoshamun — CHANGES_REQUESTED** [review]
The default value for the `buttonCopy` should be the experiment winner: `Access all features`.
I also need to validate with Tsahi and Nimrod what we want to do with the mobile version. It's a good point

**Comment by rebelchris** [comment]
@idoshamun Updated the default copy, awaiting what we need to do with the mobile text.

**Review by idoshamun — APPROVED** [review]
Looks great!

**Pull request merged**
