### PR TITLE
fix: placement of experiment allocation

### PR DESCRIPTION
**Pull request by sshanzel**
## Changes
- Remove the instance of `useFeature` on any other page but the post page.
- Render the banner through `customBanner`.

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-{number} #done

### CODE REVIEW

**Review by rebelchris — APPROVED** [review]
Forgot we even had this option.
Nothing weird to me, but maybe wait for 2 reviews 🙏

**Review by nensidosari — APPROVED** [review]
Looks good. Just one test failing, may be a flaky one.

**Review by capJavert — APPROVED** [review]
Looks good, the mistake was that it allocated users for the experiment on any page due to useFeature call right?

**Comment by sshanzel** [comment]
> Forgot we even had this option.

Yep, thankfully I worked on DnD in the past - so I kinda remember the usage.

> Looks good, the mistake was that it allocated users for the experiment on any page due to useFeature call right?

Yes, I believe that was the culprit. Otherwise, we will have to make some changes to our GrowthBookProvider.

**Comment by capJavert** [comment]
@sshanzel just check it looks like it has a bunch of failed tests (not only flaky) 🙏

**Pull request merged**
