### PR TITLE
fix: account pages when not logged in

### PR DESCRIPTION
**Pull request by sshanzel**
## Changes
- Display the login screen when viewing an account page as an anonymous user.

Feel free to check the preview deployment.

Previews:
Screenshot 2024-06-06 at 9 27 44 PM

Screenshot 2024-06-06 at 9 31 34 PM

Screenshot 2024-06-06 at 9 28 18 PM

https://github.com/dailydotdev/apps/assets/13744167/16469448-d74e-468a-a463-e73b3795382d

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

MI-380 #done

### Preview domain
https://mi-380.preview.app.daily.dev

### CODE REVIEW

**Comment by idoshamun** [comment]
@sshanzel is it possible to show in on login mode instead of signup?

**Comment by sshanzel** [comment]
> @sshanzel is it possible to show in on login mode instead of signup?

I think the reason why Tsahi wanted a screen over the popup is, that users can still close the modal and end up with an empty screen again, but yeah, we could, we will just need to have a button and some message in exchange for that.

**Comment by rebelchris** [comment]
@sshanzel I think Ido means the Login mode instead of the Signup mode by default.
Our authOptions should support that.

**Comment by idoshamun** [comment]
> @sshanzel I think Ido means the Login mode instead of the Signup mode by default.
Our authOptions should support that.

Exactly

**Comment by sshanzel** [comment]
Oh, sorry. My brain misread "mode" to modal 😂

**Comment by sshanzel** [comment]
Updated 🥳 

Screenshot 2024-06-06 at 9 50 11 PM

**Review by rebelchris — APPROVED** [review]

**Review by idoshamun — APPROVED** [review]

**Review by nensidosari — APPROVED** [review]

**Pull request merged**
