### PR TITLE
fix: optional data for when modal loading

### PR DESCRIPTION
**Pull request by rebelchris**
### Describe what this PR does
- With new later return we need to make props optional to not-break rendering.

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-1250 #done

### CODE REVIEW

**Review by capJavert — CHANGES_REQUESTED** [review]
Nice forward thinking.

I would also just add `source?.` inside `useMemberRoleForSource` and make it optional since right now `source` is expected to always be present. Not sure why linter does not flag this as error.

**Review by sshanzel — APPROVED** [review]

**Comment by rebelchris** [comment]
@sshanzel Holding off till we have that one in place and will re-look how it performs or is needed :)

**Comment by sshanzel** [comment]
I think the fix for the loading placeholder worked alright. But we can probably keep this just to be on the safe side always. Either way sounds good to me 🚢

**Review by capJavert — CHANGES_REQUESTED** [review]
We still need to make `source` optional in `UseMemberRoleForSourceProps` type, don't know why typescript is not screaming for this.

**Review by capJavert — APPROVED** [review]

**Pull request merged**
