### PR TITLE
fix: flaky tests for rank-related

### PR DESCRIPTION
**Pull request by sshanzel**
## Changes

Describe what this PR does
- fixed a condition where it always passes when since the user is not yet loaded when triggered

## Manual Testing

- On those affected packages:
- [x] Have you done sanity checks in the webapp?
- [x] Have you done sanity checks in the extension?

- Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [x] Laptop (1020px)

DD-565 #done

### CODE REVIEW

**Comment by ayadotdev** [comment]
Thank you for taking this, Lee! I have one question: what is the difference between checking `loadedUserFromCache` and just `user`?

**Review by ayadotdev — APPROVED** [review]

**Comment by sshanzel** [comment]
Is it a property that determines whether the user has been loaded already or not yet from the cache.

**Review by rebelchris — APPROVED** [review]
Sometimes life can be so simple!
Thanks for fixing this Lee 🙌

You can go ahead and merge this when you ready

**Comment by sshanzel** [comment]
Yes, it came out quite simple, though the debugging was tough 🤣

**Pull request merged**
