### PR TITLE
feat: add downvote followup CTA to feed layout v1 action buttons

### PR DESCRIPTION
**Pull request by kopancek**
## Changes

Adds the same CTA for downvoting as we had for the existing PostModal downvote action.

### Screenshot

laptop
Screenshot 2024-01-19 at 17 48 36

tablet
Screenshot 2024-01-19 at 17 54 16

mobile
Screenshot 2024-01-19 at 17 53 55

### On those affected packages:
- [X] Have you done sanity checks in the webapp?
- [X] Have you done sanity checks in the extension?
- [X] Does this not break anything in companion?

### Did you test the modified components media queries?
- [X] MobileL (420px)
- [X] Tablet (656px)
- [X] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

MI-98 #done

### CODE REVIEW

**Review by nensidosari — COMMENTED** [review]
The changes look great and ready to approve, just if we could do one more check before. 
I do get this behaviour when testing locally:

https://github.com/dailydotdev/apps/assets/36197304/1b1b8562-134e-419a-a0df-b45f3fd3a7fd

**Comment by kopancek** [comment]
> The changes look great and ready to approve, just if we could do one more check before. Was curious to see how it behaved and I do get this behaviour when testing locally:
> 
>  Screen.Recording.2024-01-22.at.6.58.10.AM.mov

I checked and something fishy is going on. The panel is part of the action buttons container, but for some reason it replaces the whole card 🤯

**Comment by nensidosari** [comment]
> I checked and something fishy is going on. The panel is part of the action buttons container, but for some reason it replaces the whole card 🤯

Yeah, v weird, was sure when looking at the code it was alright, but the behaviour doesn't match much 😬

**Comment by kopancek** [comment]
> > I checked and something fishy is going on. The panel is part of the action buttons container, but for some reason it replaces the whole card 🤯
> 
> Yeah, v weird, was sure when looking at the code it was alright, but the behaviour doesn't match much 😬

Found the problem. We had another PostTagsPanel on the article card itself 😢 Removed that and fixed another issue - the tag panel was not clickable. Now it should be 👌

**Review by nensidosari — APPROVED** [review]
LGTM

**Review by capJavert — APPROVED** [review]
🚀

**Pull request merged**
