### PR TITLE
fix: devcard icon on profile menu

### PR DESCRIPTION
**Pull request by nensidosari**
## Changes
- add the new devcard icon to profile menu - asked [here](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1715232808120619)

### Preview domain
https://fix-devcard-icon.preview.app.daily.dev

### CODE REVIEW

**Review by rebelchris — COMMENTED** [review]
But whats the other icon we already have?
I assumed we would just remove this one and use the other one?

**Review by capJavert — APPROVED** [review]
As Chris said, we should have single icon now used everywhere (if not already).

**Comment by capJavert** [comment]
@nensidosari ah I see, the `Devcard/outlined.svg` was the old icon while `Devcard/filled.svg` was the new one.

**Review by capJavert — APPROVED** [review]

**Comment by nensidosari** [comment]
So stupid 🤦‍♀️ Thanks @capJavert

**Pull request merged**
