### PR TITLE
feat: add community links env limit

### PR DESCRIPTION
**Pull request by rebelchris**
### Describe what this PR does
- Add env variable for community links per day

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-39 #done

### CODE REVIEW

**Comment by sshanzel** [comment]
I think we should add this on the API side and the validation will be part of the mutation. What do you think?

**Comment by rebelchris** [comment]
Thought about that as well, but we need the value in the frontend ui, so eitherway we'll need to share it.

**Comment by idoshamun** [comment]
This should be provided by the API in my opinion. Otherwise we would have to release a version to change it.

**Comment by rebelchris** [comment]
@idoshamun Do you have any suggestions on how we can push this back to the apps, as we need the value to display in the UI.

**Comment by idoshamun** [comment]
I think we're aligned on this looking at the DR? just making sure @rebelchris

**Pull request closed without merging**
