### PR TITLE
fix: missed rank index

### PR DESCRIPTION
**Pull request by sshanzel**
## Changes

Describe what this PR does
- Fixes missed indexes in the `RANKS` object.

## Manual Testing

- On those affected packages:
- [x] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?

DD-{number} #done

### CODE REVIEW

**Review by rebelchris — APPROVED** [review]
Are there no other places we could also need this?
Otherwise really great work 🙌

**Review by idoshamun — APPROVED** [review]
I agree with Chris. Make sure there's no other place we use the ranks without `getRank`

**Comment by sshanzel** [comment]
Thank you both for the awesome review!

@rebelchris can you please have a look at the last commit that it is valid?

**Comment by rebelchris** [comment]
@sshanzel Does seem valid yes!
It should never fail as this is a safetype check based on negative values so I think you got them all now 🙌

Thanks for going through them 🚀

**Pull request merged**
