### PR TITLE
fix: one signal dynamic import

### PR DESCRIPTION
**Pull request by sshanzel**
## Changes
- Dynamically import the package only when necessary.
- The `useQuery` already has the `enabled` property's condition to check whether the user is logged in or not.

TODO:
- ~~Test the PN on preview deployment.~~

## Events

Did you introduce any new tracking events?

## Experiment

Did you introduce any new experiments?

## Manual Testing

> [!CAUTION]
> Please make sure existing components are not breaking/affected by this PR

WT-2022 #done

### Preview domain
https://wt-2202.preview.app.daily.dev

### CODE REVIEW

**Review by capJavert — APPROVED** [review]

**Comment by sshanzel** [comment]
Still works as intended.

Screenshot 2024-10-14 at 2 33 49 PM

**Review by rebelchris — APPROVED** [review]
Nice that's an easy win!
Just have to make sure the dynamic import actually works as intended 🤞

**Comment by sshanzel** [comment]
Oh, sorry forgot to attach the screenshots. This is the before and after. Second image does not request it anymore (both are logged out).

Screenshot 2024-10-14 at 1 41 12 PM

Screenshot 2024-10-14 at 1 40 34 PM

**Comment by sshanzel** [comment]
And of course, OneSignal should be requested when logged in 🚀 

Screenshot 2024-10-14 at 3 26 57 PM

**Pull request merged**
