### PR TITLE
fix: code block paddings

### PR DESCRIPTION
**Pull request by sshanzel**
## Changes
- The fix on the multi-line code block padding should now be applied.
- Though on the inline ones, I can't seem to find the right pseudo-class to apply the proper paddings.

Fix:
image

Sketch:
Screenshot 2024-01-05 at 8 11 24 PM

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-1975 #done

### CODE REVIEW

**Review by rebelchris — APPROVED** [review]
Just need to ensure it doesn't break content for freeform posts as they re-use this.
As for the inline, it does already look good no?

**Review by capJavert — APPROVED** [review]

**Review by omBratteng — APPROVED** [review]

**Comment by omBratteng** [comment]
@rebelchris the inline is almost there, the only difference is the left/right padding when the inline codeblock breaks over multiple lines

**Comment by omBratteng** [comment]
@sshanzel could apply the `box-decoration-break: clone` (`-webkit-box-decoration-break: clone`), it would look like this
image

compared to this without
image

[1] https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break

**Comment by sshanzel** [comment]
> @sshanzel could apply the box-decoration-break: clone (-webkit-box-decoration-break: clone), it would look like this

Nice! Have been looking for the right property for some minutes already. Thank you!

**Comment by sshanzel** [comment]
> Just need to ensure it doesn't break content for freeform posts as they re-use this.

Will verify this before merging.

**Comment by sshanzel** [comment]
Freeform posts look to be fixed now 🥳 

Before:

Screenshot 2024-01-08 at 3 39 29 PM

After:
Screenshot 2024-01-08 at 3 39 20 PM

**Pull request merged**
