### PR TITLE
chore: the docker postgres images was outdated

### PR DESCRIPTION
**Pull request by rebelchris**
People where not able to spool up the apps docker image.
As mentioned before, might be worthwhile moving away from it at one stage, or rework how we want people to use it.

We don't actively maintain this image and every change on the API/Gateway can break this behaviour.

For now this fix will make sure it's up to date again.

### CODE REVIEW

**Review by idoshamun — COMMENTED** [review]
It seems that we use the same image. I'm not sure what is the change except the volumes. If the problem is the image so nothing changed there. The change you present here makes it create two databases `api` and `api_test` instead of one

**Comment by rebelchris** [comment]
Not sure what the issue was, but I generally just make these inline with the docker configs for the individual projects as we use them.

The postgres was failing, so thought we might have introduced the second database and it failed on that?

**Comment by idoshamun** [comment]
I haven't checked if it fails but if you confirmed locally that it works than we're all set and I can approve it

**Comment by rebelchris** [comment]
@idoshamun Yep, ran the previous version, fails on Postgres, made these changes and it spools up correctly.

**Review by idoshamun — APPROVED** [review]

**Comment by tevez07b9** [comment]
@rebelchris , I took the latest pull form master but both api and postgres containers keep crashing
image

Please help

**Comment by jonatan5524** [comment]
> @rebelchris , I took the latest pull form master but both api and postgres containers keep crashing image
> 
> Please help

experiencing the same behavior  Permission denied, daily-postgres crashes:
image

System: Ubutnu 20.04.3 LTS
Docker: Docker version 20.10.13
Docker-compose: docker-compose version 1.29.2

**Comment by rebelchris** [comment]
@tevez07b9 @jonatan5524 I've found and solved a small bug in our docker setup.
Would you mind trying it again?

Try to pull the latest master version first.

Since it failed you'll have to full down everything with the following command:

```bash
docker-compose down --volumes
```

Then re-up them:

```bash
docker-compose pull && docker-compose up
```

It might occur the gateway fails on the first boot, you can manually start that one again once everything else is up.

**Comment by tevez07b9** [comment]
Everything works, thank you so much @rebelchris

**Comment by jonatan5524** [comment]
> @tevez07b9 @jonatan5524 I've found and solved a small bug in our docker setup. Would you mind trying it again?
> 
> Try to pull the latest master version first.
> 
> Since it failed you'll have to full down everything with the following command:
> 
> ```shell
> docker-compose down --volumes
> ```
> 
> Then re-up them:
> 
> ```shell
> docker-compose pull && docker-compose up
> ```
> 
> It might occur the gateway fails on the first boot, you can manually start that one again once everything else is up.

Worked! thank you.

**Pull request merged**
