### PR TITLE
fix: interactiveness of mention popup

### PR DESCRIPTION
**Pull request by sshanzel**
### Describe what this PR does
- In my previous PR we introduced manual handling of state on where we should display the tooltip or not. Unfortunately, it introduced an edge case where the popup lost its interactiveness.
- Also refactored the use debounce hook to be cancellable
- Fixed the primary concern in this PR

Verified workability in this link: https://daily-webapp-i28cjgu9g-dailydotdev.vercel.app/posts/RcIbqXVDf

### On those affected packages:
- [x] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

DD-{number} #done

### CODE REVIEW

**Review by rebelchris — CHANGES_REQUESTED** [review]
I think the code is fine, but I did spot two issues (probably not related to this issue)

Issue one:
When scrolled up top the mention bounces in and out by loosing focus:
test

And issue two is a bit of the opposite
When scrolling the mention down it shows the popup half way over the mention.
The orange line is actually where the mention sits.
Screenshot 2022-03-25 at 14 25 42

Would you mind looking into those?
Especially issue 1?

**Comment by sshanzel** [comment]
@rebelchris thank you for the review! There is indeed a bug where it pops in and out. Regarding the second issue. Unfortunately, that's unavoidable, it is due to the fact that our tooltip has large height and when the screen doesn't fit anymore on both ends, it would need to adjust a bit which results to tooltip overlapping the reference. What do you think?

**Comment by sshanzel** [comment]
@rebelchris let me know if you want me to make a bit more adjustments here. Thank you! 🙌

**Review by rebelchris — APPROVED** [review]
@sshanzel Nice work, looks to work way better now!
I did note sometimes it takes a very long time to show up (especially for Ido)
Just remember to log a ticket for that.

**Comment by sshanzel** [comment]
@rebelchris thank you for the review! Ah, yes, let me log it now! 🚢

**Pull request merged**
