### PR TITLE
feat: better query client config for development

### PR DESCRIPTION
**Pull request by capJavert**
### Describe what this PR does
- As discussed added default query client config which can be used to provide defaults for all queries
- Disabled refetch on window focus in development
  - Idea is to prevent all the recurring fetches of active queries (eg. boot) when developing and constantly focusing in/out of the editor/devtools etc. 

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-{number} #done

### CODE REVIEW

**Comment by capJavert** [comment]
@rebelchris I had a type mismatch for `QueryClientConfig` due to different versions of `react-query` existing in different packages. Bumped everything to to match `webapp` version `3.39.1`. I see you also bumped like this (but to latest version) in #1628 so it should be good. `react-query` also did not have any breaking changes during `3.x` cycle.

**Review by sshanzel — APPROVED** [review]
Thanks for adding this! 🚢

**Review by rebelchris — APPROVED** [review]
Nice work Ante!
Also thanks for aligning the react-query version.

Did you figure out how the npm update works with our internal packages? (Mainly wondering if it's clearly documented somehwere)

**Comment by capJavert** [comment]
> Nice work Ante! Also thanks for aligning the react-query version.
> 
> Did you figure out how the npm update works with our internal packages? (Mainly wondering if it's clearly documented somehwere)

@rebelchris I did it manually in package.json this time, but while back when I was working with lerna I would do it with `npm` through `lerna run --scope package`

**Pull request merged**
