### PR TITLE
fix: devcard overlap on sidebar

### PR DESCRIPTION
**Pull request by sshanzel**
## Changes

The sidebar overlaps on the content - we have now changed the breakpoints.

Max size before breaking:
Screen Shot 2022-02-10 at 7 11 45 PM

## Manual Testing

- On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?

DD-{number} #done

### CODE REVIEW

**Review by rebelchris — APPROVED** [review]
Cool!

Thanks for checking this

**Review by idoshamun — CHANGES_REQUESTED** [review]
I think the gap should change breakpoint accordingly, isn't it?

**Comment by sshanzel** [comment]
@idoshamun it used to be not. Let me try and check this approach.

**Comment by idoshamun** [comment]
@sshanzel I mean instead of `laptop:gap-20"` use `laptopL:gap-20`

**Comment by sshanzel** [comment]
@idoshamun looked perfect with your suggestion! 🚀 

image

**Comment by sshanzel** [comment]
@idoshamun yes I did, having the initial change would break immediately on laptop screen. I think this was forgotten to be considered when the sidebar change was designed. Should we reach out to Tsahi on how he would want it in consideration of the sidebar?

**Comment by idoshamun** [comment]
Yes. This would be the best

**Comment by sshanzel** [comment]
After discussing with Tsahi on what should be the final layout, he mentioned that we should set specific size on the devcard itself and the textarea (will vary based on screen size). Then on laptop it should still be on the same row.

Have also checked different screen sizes and still displaying as intended.

image

**Pull request merged**
