### PR TITLE
feat: allow filtering of squads

### PR DESCRIPTION
**Pull request by rebelchris**
## Changes

Frontend for showing the squad filter.

[squad-filter.webm](https://github.com/user-attachments/assets/fae8308b-b8ac-40e9-bab5-ba361822b5b0)

Related API:
https://github.com/dailydotdev/daily-api/pull/2304

## Events

Did you introduce any new tracking events?

## Experiment

Did you introduce any new experiments?

## Manual Testing

> [!CAUTION]
> Please make sure existing components are not breaking/affected by this PR

AS-625 #done 

### Preview domain
https://as-625-squad-filter.preview.app.daily.dev

### CODE REVIEW

**Review by omBratteng — APPROVED** [review]
LGTM, though want to test in preview once API is merged

**Review by nensidosari — APPROVED** [review]
Looks good, just one thing to check before merging.
Since we have these also able to be filtered on onboarding, please make sure to test onboarding as well that this is included.

**Comment by rebelchris** [comment]
@omBratteng Tested on the preview and works as intended for me :) 
@nensidosari Checking now.

**Comment by nensidosari** [comment]
From the tests I did looks all good on both scenarios

**Pull request merged**
