### PR TITLE
feat: add react hooks eslint plugin

### PR DESCRIPTION
**Pull request by capJavert**
## Changes

**See for latest decision https://dailydotdev.atlassian.net/wiki/spaces/HAN/pages/512491748/WT-1235+ESlint+Rules+of+Hooks**

Shared lint result:
`172 problems (21 errors, 151 warnings)` - bunch of issues 

Extension lint result (most of the issues):
`23 problems (11 errors, 12 warnings)`

At the end it is important to note that with these kind of changes (especially `useEffect` fixes) we need to be careful not to introduce bugs since some of this issues contain anti patterns that went below the radar during development of our applications up until this point.

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-1235 #done

### CODE REVIEW

**Comment by capJavert** [comment]
@rebelchris there are still a lot of linter issues, `shared` has most of course since the most codebase is there. I do agree that this should be done in one go but from my points in description I think if we blindly follow lint warnings we will not get any better codebase and maybe even have worst rendering performance.

I can do this incrementally day by day (for 30minutes in parallel with squads v5 tasks) and clear up the issues as I did for web app, but from review point of view I think it would be better to look at it in chunks. If you look at the commits already in the PR there are different cases and types of fixes to solve issues with react-hooks. Some issues are not really solvable without changing implementation like this one https://github.com/dailydotdev/apps/pull/1745/commits/f0177886ba984fb7ca4a9fe228a0c7ef0d644332

Curious if you are fine with this ending up being large PR or would favor incremental adoption (which we would have to find the best way to do it). FYI @sshanzel 

Alternative is that we could ignore `useEffect` errors for now (since those are most complex but might actually have some "side effects" pun intended in them that actually cause bugs we don't see), and strive to only solve memoization (useMemo and useCallback) which are easy fixes 99% of the time.

**Comment by rebelchris** [comment]
@capJavert I see I actually never commented on here.
But my suggestion try to introduce this as just a info state ([if possible](https://eslint.org/docs/latest/use/configure/rules) warn maybe?)
and we can do small PR's over time fixing the issues.

Until we get to a point where there are none, where we'll set it to strict.

**Comment by capJavert** [comment]
@rebelchris @sshanzel from team meeting last week I took some time yesterday to add this, would appreciate if you have any more comments, most of the stuff is now explained in [the DR](https://dailydotdev.atlassian.net/wiki/spaces/HAN/pages/512491748/WT-1235+ESlint+Rules+of+Hooks) which is also linked in description.

**Review by rebelchris — APPROVED** [review]
wow nice find :D

**Review by idoshamun — APPROVED** [review]

**Pull request merged**
