### PR TITLE
fix: convert webapp requests to api directly

### PR DESCRIPTION
**Pull request by rebelchris**
### Describe what this PR does
- We had some legacy code that for the webapp routed traffic internally first
- We now remove this to directly call API and avoid re-routing latency (potentially, probably low impact)

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-1886 #done

### CODE REVIEW

**Review by idoshamun — APPROVED** [review]

**Comment by idoshamun** [comment]
@rebelchris I actually see that it breaks live previews. Maybe we should enable it only for previews?

**Comment by rebelchris** [comment]
@idoshamun We actually where wondering if we could simple allow these generic vercel sub domains as a origin?
Maybe the easier solution in the long term.

**Review by capJavert — COMMENTED** [review]
Having API on separate domain will add CORS requests to each request. Most of the time that is worst then just reverse proxy routing through webapp `/api` as we had now.

**Comment by idoshamun** [comment]
@capJavert are you sure it'll add cors even on `app.daily.dev` and `api.daily.dev`. I don't remember the exact rules of cors but they share the same primary domain

**Comment by capJavert** [comment]
@idoshamun yes, its a matter of `origin` and subdomain is different `origin`.

**Pull request merged**
