### PR TITLE
fix: similar post empty state text

### PR DESCRIPTION
**Pull request by rebelchris**
### Describe what this PR does
- Request to show different text if post title is not available/found.

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

AS-333 #done

### Preview domain
https://as-333-similar-post-empty-state.preview.app.daily.dev

### CODE REVIEW

**Review by sshanzel — COMMENTED** [review]
Should we disable the button itself so they won't have to get redirected?

**Comment by rebelchris** [comment]
We dont know until we load the page if they're are any.

**Comment by sshanzel** [comment]
>  We dont know until we load the page if they're are any.

Ah, this is the empty screen. I thought this was the panel you click. Yeah, this looks good 🚀

**Review by sshanzel — APPROVED** [review]
:shipit:

**Review by nensidosari — APPROVED** [review]

**Pull request merged**
