### PR TITLE
fix: devcard responsiveness

### PR DESCRIPTION
**Pull request by sshanzel**
Screen Shot 2021-11-07 at 8 34 30 PM

### CODE REVIEW

**Comment by sshanzel** [comment]
1080p:

Screen Shot 2021-11-07 at 8 35 17 PM

**Review by idoshamun — APPROVED** [review]
You are super fast!!

**Comment by idoshamun** [comment]
Please make sure to add "Closes #670" in the merge PR

**Comment by sshanzel** [comment]
Woohoo! Thank you for the tip on how to close the issue automatically.

**Pull request merged**
