### PR TITLE
fix: refactor ad placement for squads

### PR DESCRIPTION
**Pull request by rebelchris**
### Describe what this PR does
- The request was to put ads not in the first place for squads.
- I added a extra criteria to only add a ad if there are at least 2 posts (so it doesn't show after welcome post)
- And added the option to add the ad preferably in 3th spot

I tried to make it as dynamic as possible, unfurtionally we don't really support great feed config per feed, something I think we should invest in down the line (talked about this before) 
For now this felt least intrusive and lean.

@idoshamun From your perspective would love to hear if it harms metrics that we perform the query for ads, but optionally don't render them? 
I thought about not querying at all, but it would delay the page

My feed: (unchanged)
Screenshot 2023-10-12 at 10 37 09

Empty squad (only welcome)
Screenshot 2023-10-12 at 10 37 16

Filled squad (after 3th position)
Screenshot 2023-10-12 at 10 37 23

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-{number} #done

### CODE REVIEW

**Review by omBratteng — APPROVED** [review]
Good change

**Review by DragosIorgulescu — APPROVED** [review]
nice 👌  not sure if `adPostLength` is immediately obvious naming on what it's role is, but #naming_things_is_hard

**Comment by rebelchris** [comment]
@DragosIorgulescu lol for sure, that one even took me longest to come up with.
Not sure if any of these work better:
`showsAdsWhenPostExceedsLength` 
`minimumPostForAds`

Or any alternative is welcome 🤗

**Comment by DragosIorgulescu** [comment]
> @DragosIorgulescu lol for sure, that one even took me longest to come up with. Not sure if any of these work better: `showsAdsWhenPostExceedsLength` `minimumPostForAds`
> 
> Or any alternative is welcome 🤗

the only other one that comes to mind is `adPostPosition` maybe?

**Comment by rebelchris** [comment]
@DragosIorgulescu That sounds more like adPosition which we already have.
This one is more how many post should be there to even render a ad.

**Comment by idoshamun** [comment]
@rebelchris Unfortunately, we can't allow querying without rendering it will reduce our reported CTR and can make us less attractive. Good that explicitly asked about it!

**Comment by rebelchris** [comment]
@idoshamun Ok thanks, let me see what I can change to prevent the query and the render both :)

**Comment by rebelchris** [comment]
@idoshamun Refactored the load to optimize non blocking other feeds from rendering.

**Review by idoshamun — APPROVED** [review]
Looks great

**Pull request merged**
