### PR TITLE
refactor: make sidebar popular feed link dynamic

### PR DESCRIPTION
**Pull request by ayadotdev**
Added AB testing for sidebar popular feed link copy.

DD-422 #done

### CODE REVIEW

**Review by idoshamun — APPROVED** [review]
Perfect!

**Review by rebelchris — CHANGES_REQUESTED** [review]
We actually also load the feed name on the `MainFeedLayout` please make sure to also include this new name there.

Screenshot 2022-01-11 at 13 09 33

**Comment by idoshamun** [comment]
@rebelchris nice catch!

**Review by rebelchris — APPROVED** [review]
Nice work! 👏

**Review by sshanzel — APPROVED** [review]
Awesome! 🚀

**Pull request merged**
