### PR TITLE
fix: connected users flow

### PR DESCRIPTION
**Pull request by sshanzel**
## Changes
- I have totally missed this, but after testing, now that we have more requirements for allowing the sign back flow, we will have to update the connected methods flow. Previously we were just showing the connected provider on the top-most row. Now we need to display the user's information too.
- Thankfully we fetch all that during the process.

Preview:

https://github.com/dailydotdev/apps/assets/13744167/690c0c58-6e3c-435e-aa36-bf77e0c7e8ec

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-{number} #done

### CODE REVIEW

**Comment by sshanzel** [comment]
@rebelchris this should now have cleared the existing flow. With the concern on the copy, do we wait for the updates or we can merge this now once verified and approved?

**Comment by sshanzel** [comment]
@dailydotdev/web-team should be ready for review.

**Review by rebelchris — APPROVED** [review]
Looks good, as critical be sure to apply critical tests on deployment 🙏

**Comment by sshanzel** [comment]
> Looks good, as critical be sure to apply critical tests on deployment 🙏

Yep. Have done a lot of tests on preview deployment, will do it again on prod.

**Pull request merged**
