### PR TITLE
fix: onboarding trap

### PR DESCRIPTION
**Pull request by sshanzel**
### Describe what this PR does
- One issue could be a race condition where we were not awaiting the variable we use when updating them, then the useEffect gets triggered to open the modal again. This would ensure setting the value has happened first before closing them modal.

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-{number} #done

### CODE REVIEW

**Review by rebelchris — APPROVED** [review]
Wouldn't this delay the closing of the modal as well?
We can give it a try though.

**Comment by sshanzel** [comment]
> We can give it a try though.

I noticed a slight delay compared to the subsequent closes of modal. WDYT?

**Comment by sshanzel** [comment]
@rebelchris even waiting for local cache fails probably due to some inaccuracies with the update of the flags. Local flags may have a value of v1 but then now we released the `v2`, then waiting for local values is not correct.

We should instead wait for when the first boot data is fetched.

**Review by rebelchris — APPROVED** [review]
Alright seems good to me.

**Pull request merged**
