### PR TITLE
feat: changing welcome image to max-width and not fixed

### PR DESCRIPTION
**Pull request by TomDowling**
## Changes
The welcome post was using a fixed width image so was breaking mobile i changed this to a max-width instead

### Describe what this PR does
- Short and concise, bullet points can help
- Screenshots if applicable can also help

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-1372 #done

### CODE REVIEW

**Review by sshanzel — COMMENTED** [review]
Code-wise looks good to me. But can you provide a screenshot of how it looks like on both mobile and desktop?

**Comment by TomDowling** [comment]
@sshanzel Apologies here are some screenshots for examples

Mobile
Screenshot 2023-05-18 at 7 10 04 pm


Desktop
Screenshot 2023-05-18 at 7 12 21 pm

**Review by sshanzel — APPROVED** [review]
Looks amazing!! 🤩

**Review by sshanzel — APPROVED** [review]
Looks amazing!! 🤩

**Pull request merged**
