### PR TITLE
refactor: file format to use

### PR DESCRIPTION
**Pull request by sshanzel**
## Changes
- The SVG we generate from the API has the complete meta tags in order to work when sharing through Twitter. We need to set it as the default.

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-{number} #done

### CODE REVIEW

**Review by nensidosari — APPROVED** [review]
Looks good to me, not sure if we had any requirements to actually have this as a png though? 🤔

**Review by rebelchris — APPROVED** [review]
Also not sure if changing to SVG has other implications.
We have to be quite save with this, can we validate it first on preview?

(EG maybe mobile can't handle this)

**Review by kopancek — CHANGES_REQUESTED** [review]
I would be very careful here. I don't think pointing to the svg is the right way forward. See slack discussion: https://dailydotdev.slack.com/archives/C06FDFQC6QZ/p1708079777148659?thread_ts=1708078656.377809&cid=C06FDFQC6QZ

**Comment by nensidosari** [comment]
Decided to close this based on discussion in slack: https://dailydotdev.slack.com/archives/C06FDFQC6QZ/p1708328543387319?thread_ts=1708002083.892319&cid=C06FDFQC6QZ

**Pull request closed without merging**
