### PR TITLE
feat: remember scroll position and restore after post modal close

### PR DESCRIPTION
**Pull request by capJavert**
### Describe what this PR does
- I could not really get anything concrete on this so wanted to propose a different approach
  - I also checked and this does not happen on Android phones I have on me Android 12 and 13
  - As said in tasks and reports seems like iOS only issue when clicking "X" close button
  - Also, if user just uses back button (instead of "X") scroll restoration works and they do not get jumped to top 
- To fix this I implemented a ref to save scroll position on feed when post modal gets opened, I keep it and when modal is closed by clicking on "X" I just restore that position and that works
  - also it does not break desktop/other platforms since they just retain scroll normally
  
I know this does not fix the core issue but if iOS browser was conforming to the spec this would not even be the problem so I think if this works and brings a lot of value to our users it should be enough.
  
It can be tested on [preview2](https://preview2.app.daily.dev)

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-812 #done

### CODE REVIEW

**Comment by capJavert** [comment]
Related to https://github.com/dailydotdev/apps/pull/1749

**Comment by rebelchris** [comment]
@capJavert The only issue is still other modals though.
So the article modal now works, but for instance opening the customize window and closing that will always reset scroll position. (Maybe it's a edge-case we can live with, but logging it here)

**Comment by capJavert** [comment]
> What is the performance impact of this proposal?

I don't think there is any performance impact. 

> So the article modal now works, but for instance opening the customize window and closing that will always reset scroll position. (Maybe it's a edge-case we can live with, but logging it here)

We can re-apply this logic to lazy modals I would think. We just need to hook into open/close events and add the ref to save the scroll position. This open post -> back to post is probably most used so it gives users the best gain.

**Comment by idoshamun** [comment]
I can't test (no iOS device) but code wise it looks great.
Should we consider adding as Ante suggested to the modals hooks instead of this specific one?
This way we'll make sure it won't happen with any other modal

**Review by idoshamun — APPROVED** [review]

**Comment by capJavert** [comment]
@rebelchris should I merge this then and add a backlog item to update/test this on lazy modal too? 

Don't wanna block this since we focus on onboarding and squad v5 this week.

**Comment by rebelchris** [comment]
@capJavert Yes go ahead and merge this, can you take care of the backlog ticket for this for now?

**Pull request merged**
