### PR TITLE
fix: extension comment modal size

### PR DESCRIPTION
**Pull request by kirillkurko**
### Describe what this PR does

Now we use tailwind class instead of inline style, so it's our plugin can convert it from rem to pixels and it's solves issue with modal height in companion and we don't rely on site font size

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [x] Have you done sanity checks in the extension?
- [x] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

DD-{number} #done

### CODE REVIEW

**Review by rebelchris — APPROVED** [review]
Nice one! Did you validate the output is now in pixels?

**Comment by sshanzel** [comment]
@kirillkurko kindly validate in the preview deployment in the webapp as well since the reason we were not using tailwindcss arbitrary value is, that it's unstable. Sometimes it generates the desired value sometimes it does not with our current setup with the webapp.

**Comment by kirillkurko** [comment]
> @kirillkurko kindly validate in the preview deployment in the webapp as well since the reason we were not using tailwindcss arbitrary value is, that it's unstable. Sometimes it generates the desired value sometimes it does not with our current setup with the webapp.
> 
> Note: the issue I mentioned is on production build.
> 
> You can set this up in one of our vercel's preview deployment, so the comment box can actually be shown.

Got it, okay, but now issue with login blocks the testing, because I cannot sigh up to deployed preview

**Comment by sshanzel** [comment]
> Got it, okay, but now issue with login blocks the testing, because I cannot sigh up to deployed preview

Yes, we have preview deployments in Vercel where it would allow login. If you haven't tried it in our setup, just let me know, and I'll walk you through how to set it up.

**Comment by kirillkurko** [comment]
> Yes, we have preview deployments in Vercel where it would allow login. If you haven't tried it in our setup, just let me know, and I'll walk you through how to set it up.

It will great if you will show me it

**Review by sshanzel — APPROVED** [review]
Woop! Woop! Tested it out in preview deployment, and it worked! 🚢

**Pull request merged**
