### PR TITLE
refactor: squads directory to fetch featured public squads only

### PR DESCRIPTION
**Pull request by sshanzel**
## Changes
- In coordination with making the API accept a boolean property to filter by flags.
- Reference: https://github.com/dailydotdev/daily-api/pull/1902

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

MI-348 #done

### Preview domain
https://mi-348.preview.app.daily.dev

### CODE REVIEW

**Review by kopancek — CHANGES_REQUESTED** [review]
Looks good to me. Blocking now, until the related API PR is merged.

**Review by rebelchris — CHANGES_REQUESTED** [review]
Looks good indeed.
As @kopancek says blocking till API is merged, as well as current public squads are converted to featured = true 🙏

**Comment by sshanzel** [comment]
@rebelchris @kopancek this is only pointed to the intermediate branch, meaning, this will not affect prod.

**Comment by kopancek** [comment]
> @rebelchris @kopancek this is only pointed to the intermediate branch, meaning, this will not affect prod. But yeah, we can wait for the API to be merged.

Didn't notice that. In that case, feel free to merge to the intermediate branch :)

**Review by kopancek — APPROVED** [review]

**Review by nensidosari — APPROVED** [review]
Approving since we have @rebelchris blocking still. 
But @sshanzel this does not need to be merged in the intermediate branch, we want this feature released right away.

**Review by rebelchris — APPROVED** [review]
Query was run anyway :)

**Comment by sshanzel** [comment]
Should be merged now 🥳

**Pull request merged**
