### PR TITLE
#1000 fix BUG: on mobile the header is missing the app's logo

### PR DESCRIPTION
**Pull request by whovishnu**
Hi,
Fix App's Logo Missing in Mobile.

### CODE REVIEW

**Review by rebelchris — CHANGES_REQUESTED** [review]
Thanks for the adjustments. 🥳 

It looks like with these changes we actually don't use `mobileTitle` anymore, I think we can safely remove it.
Perhaps also refactor the `showOnlyLogo`? (not sure if we only use it sometimes)

**Comment by whovishnu** [comment]
@rebelchris welcome,
so i will remove `mobileTitle` and by default will be  `showOnlyLogo`.

**Review by rebelchris — APPROVED** [review]
Thank you so much,
looks good to me, just waiting for @sshanzel to review as he manages the OS contributions :)

**Review by sshanzel — APPROVED** [review]
Wow! Thank you so much for the fix and the cleanup itself. I always love when the deleted code is greater than the new ones. Well done indeed 👏

**Comment by sshanzel** [comment]
@rebelchris have verified on the preview, it works as intended 🥳

**Pull request merged**
