### PR TITLE
fix: added range for changelog width to not span to full width

### PR DESCRIPTION
**Pull request by capJavert**
### Describe what this PR does
- changelog would span full width due to absolute positioned element not wrapping by default

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-{number} #done

#### Webapp
* [Long summary text (max 300 chars)](https://user-images.githubusercontent.com/9803078/224270051-82e5e9e9-d06b-45dc-96f6-5de6c3cca8e1.png)
* [Short summary text](https://user-images.githubusercontent.com/9803078/224270046-36fe5e9e-4a78-48e0-9399-5adcad90931b.png)
* [No summary](https://user-images.githubusercontent.com/9803078/224270044-c9983e0c-687b-421f-8fd8-0d23800c8500.png)

#### Extension
* [Long summary text (max 300 chars)](https://user-images.githubusercontent.com/9803078/224270048-6baf4d94-6907-47cd-ada1-97baac0ecb11.png)
* [Short summary text](https://user-images.githubusercontent.com/9803078/224270045-05a35d70-c961-48a9-9ef5-a1d762da8044.png)
* [No summary](https://user-images.githubusercontent.com/9803078/224270040-2b417d10-444e-4a06-bd47-5e55938c9730.png)

### Testing steps
Update `lastChangelog` column in the `alerts` table for your user to some date in the past. For seeded db content locally anything in `2017` works.

### CODE REVIEW

**Review by sshanzel — APPROVED** [review]
Thanks for the quick fix! 🚢

**Comment by sshanzel** [comment]
Would it be possible to replicate this locally? Just to see it works as intended now.

**Review by rebelchris — CHANGES_REQUESTED** [review]
Nice, just noticed something different locally.
The close button should be medium in spec:

Screenshot 2023-03-10 at 13 05 58

If you can fix that one we good.

**Comment by capJavert** [comment]
> Nice, just noticed something different locally. The close button should be medium in spec:
> 
> Screenshot 2023-03-10 at 13 05 58
> 
> If you can fix that one we good.

@rebelchris Tomer requested to use the smaller one, don't know if it was updated in design https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1677596825483979?thread_ts=1677595710.904269&cid=C01L0QXQJNB I might have used the wrong component. Is there a mini close icon?

**Comment by rebelchris** [comment]
@capJavert I see they updated close buttons to use `MiniClose` icon it should become a new component then.
Also in Modals, but let's leave it for now we'll have to align with Design first how they want this to happen.

Where was this communication just for my reference?

**Review by rebelchris — APPROVED** [review]

**Comment by capJavert** [comment]
> @capJavert I see they updated close buttons to use `MiniClose` icon it should become a new component then. Also in Modals, but let's leave it for now we'll have to align with Design first how they want this to happen.
> 
> Where was this communication just for my reference?

@rebelchris slack thread [here](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1677596825483979?thread_ts=1677595710.904269&cid=C01L0QXQJNB). I do see you commented already.

**Pull request merged**
