### PR TITLE
Make the article title clickable on the article page

### PR DESCRIPTION
**Pull request by Dhaiwat10**
Related to [this](https://github.com/dailydotdev/daily/issues/298) issue.

### CODE REVIEW

**Comment by Dhaiwat10** [comment]
I don't understand why the package.lock files got changed 🤔

**Comment by idoshamun** [comment]
@Dhaiwat10 thanks for the PR.
The lock files changed because you use npm 7 which changed the format of the lock files.
Please make sure to install npm 6 or you could just revert back the lock files changes and it should be fine.

**Comment by Dhaiwat10** [comment]
Oh, I see. Let me solve this :)

**Comment by Dhaiwat10** [comment]
Not sure why the PR closed itself, re-opening.

**Review by idoshamun — APPROVED** [review]
LGTM! 🤘

**Pull request merged**
