### PR TITLE
fix: onboarding scroll block placement

### PR DESCRIPTION
**Pull request by sshanzel**
## Changes
- Did a refactor to move out certain const to keep the render function lean.
- Introduced a property on the container to place certain elements after the feed's grid. Everything about the fix should only be in this commit https://github.com/dailydotdev/apps/commit/b49ba3ca13da4c2eba4626f98e3063ef00d3ddb5

Preview:

Screenshot 2023-08-02 at 5 13 43 PM

### Describe what this PR does
- Short and concise, bullet points can help
- Screenshots if applicable can also help

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-1612 #done

### CODE REVIEW

**Review by rebelchris — APPROVED** [review]
Looks great!
As it's high impact (registration) could you just double check once merged to see all is good? 🙏

**Comment by sshanzel** [comment]
> Looks great!
As it's high impact (registration) could you just double check once merged to see all is good? 🙏

Definitely. I will go through each screen size once merged. On preview, this is how it looks like
Screenshot 2023-08-02 at 5 39 18 PM
Screenshot 2023-08-02 at 5 39 10 PM

**Comment by sshanzel** [comment]
Live 🥳 

Screenshot 2023-08-02 at 5 45 07 PM
Screenshot 2023-08-02 at 5 44 52 PM

**Comment by sshanzel** [comment]
> @sshanzel Also meant just test the signup once via that element 🙏

Oh, right. Yes, it has worked as intended, adding the selected tags to the feed too 🚀

**Pull request merged**
