### PR TITLE
fix: upload toast if verify fails early

### PR DESCRIPTION
**Pull request by rebelchris**
### Describe what this PR does
- If our JS based verification failed we didn't show anything.
- So if user tries to upload wrong type of file he would never know.

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-1531 #done

### CODE REVIEW

**Comment by rebelchris** [comment]
@sshanzel Would like a review from you especially 🙏

**Review by TomDowling — APPROVED** [review]

**Review by sshanzel — APPROVED** [review]
Thanks for utilizing the same message from a single source 🚢

**Comment by sshanzel** [comment]
One thing though, the `verifyFile` function is used in a loop, so if the user tried to upload two files that are wrong, the toast will trigger twice. Nothing blocking, but just wanted it to be known.

**Comment by rebelchris** [comment]
@sshanzel Did see that indeed, not quite sure how you can upload more, I think from what I've seen we limit the picker to one?
But regardless the two toast is acceptable for now.

**Comment by sshanzel** [comment]
Dragging multiple files at the same time allows multiple uploads. Similar to GH upload. Probably the picker must be updated to allow multiple files.

> But regardless the two toast is acceptable for now.

I agree, shouldn't be too noticeable making it reset due to numerous toast.

**Pull request merged**
