### PR TITLE
fix: the side border does not span to the bottom

### PR DESCRIPTION
**Pull request by Abhi-Bohora**
## Changes

Linked Issue:  (https://github.com/dailydotdev/daily/issues/1370)

When you log in and go to Account Details, the side border was not reaching to the bottom. This PR fixes that.

Before
before
After
after

## Events

Did you introduce any new tracking events?

## Experiment

Did you introduce any new experiments?

## Manual Testing

> [!CAUTION]
> Please make sure existing components are not breaking/affected by this PR

### CODE REVIEW

**Review by rebelchris — CHANGES_REQUESTED** [review]
Thanks for this PR, it does seem to add a extra space on the right side now.
As well as a global scrollbar extra. (see screenshot)

Screenshot 2024-10-04 at 10 31 43

**Comment by Abhi-Bohora** [comment]
Thanks for looking at , This should fix the issue

**Review by rebelchris — APPROVED** [review]
Nice this seems to work :) 
Thanks!

Just waiting for @sshanzel to approve and we can merge

**Review by sshanzel — APPROVED** [review]
Nice! Tested it too and looks amazing. Thank you the effort! 🙏 ❤️ 

@rebelchris thank you for the early review 🥳 🚀

**Pull request merged**
