### PR TITLE
Lint config for checking typos in the code

### PR DESCRIPTION
**Pull request by xnivaxhzne**
### Describe what this PR does
This PR is created in response for [this comment](https://github.com/dailydotdev/apps/pull/2052#pullrequestreview-1584377610) by @rebelchris 
This PR adds a new lint script to check for typos in the code. 
This lint script will be part of pretest script.
This also fixes a typo in the code.

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [x] Have you done sanity checks in the webapp?
- [x] Have you done sanity checks in the extension?
- [x] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-{number} #done

### CODE REVIEW

**Comment by sshanzel** [comment]
Thank you for the initiative! Would it be possible for you to check the eslint plugin relevant to this?

**Comment by kavinkuma6** [comment]
> Thank you for the initiative! Would it be possible for you to check the eslint plugin relevant to this?

@sshanzel 
After my analysis, found that there is an [es-lint plugin](https://www.npmjs.com/package/@cspell/eslint-plugin) for that.

But, as mentioned [here](https://www.npmjs.com/package/@cspell/eslint-plugin#in-combination-with-cspell), the underlying implementation to parse and check the spelling are different. Because of that, we have lot of limitations in the eslint plugin. I have tried it in my local. 

One of them is, it cannot check for compound words, whereas the core package [allows us to do it](https://github.com/dailydotdev/apps/blob/e6198424d3183ff8e5c9b8af73ff83a5ef6b57c0/.cspell/cspell.json#L17).   


Anyway, [requested for clarification](https://github.com/streetsidesoftware/cspell/discussions/4781) in the respective repo.
Will wait and confirm the same here.

**Comment by sshanzel** [comment]
> > Thank you for the initiative! Would it be possible for you to check the eslint plugin relevant to this?
> 
> @sshanzel After my analysis, found that there is an [es-lint plugin](https://www.npmjs.com/package/@cspell/eslint-plugin) for that.
> 
> But, as mentioned [here](https://www.npmjs.com/package/@cspell/eslint-plugin#in-combination-with-cspell), the underlying implementation to parse and check the spelling are different. Because of that, we have lot of limitations in the eslint plugin. I have tried it in my local.
> 
> One of them is, it cannot check for compound words, whereas the core package [allows us to do it](https://github.com/dailydotdev/apps/blob/e6198424d3183ff8e5c9b8af73ff83a5ef6b57c0/.cspell/cspell.json#L17).
> 
> Anyway, [requested for clarification](https://github.com/streetsidesoftware/cspell/discussions/4781) in the respective repo. Will wait and confirm the same here.

Thank you very much for connecting with the plugin team, from their response, it seems compound words are allowed. Let me know if you are still interested in this PR. Else, we can close this one. With that, we appreciate the time and effort you've spent here 🙏

**Comment by kavinkuma6** [comment]
> > > Thank you for the initiative! Would it be possible for you to check the eslint plugin relevant to this?
> > 
> > 
> > @sshanzel After my analysis, found that there is an [es-lint plugin](https://www.npmjs.com/package/@cspell/eslint-plugin) for that.
> > But, as mentioned [here](https://www.npmjs.com/package/@cspell/eslint-plugin#in-combination-with-cspell), the underlying implementation to parse and check the spelling are different. Because of that, we have lot of limitations in the eslint plugin. I have tried it in my local.
> > One of them is, it cannot check for compound words, whereas the core package [allows us to do it](https://github.com/dailydotdev/apps/blob/e6198424d3183ff8e5c9b8af73ff83a5ef6b57c0/.cspell/cspell.json#L17).
> > Anyway, [requested for clarification](https://github.com/streetsidesoftware/cspell/discussions/4781) in the respective repo. Will wait and confirm the same here.
> 
> Thank you very much for connecting with the plugin team, from their response, it seems compound words are allowed. Let me know if you are still interested in this PR. Else, we can close this one. With that, we appreciate the time and effort you've spent here 🙏

@sshanzel let me check and do an update in sometime. Thank you.

**Comment by sshanzel** [comment]
Closing since there hasn't been any movement on this end. Thank you for the effort 🙏

**Pull request closed without merging**
