### PR TITLE
fix: comment mention on multiple lines

### PR DESCRIPTION
**Pull request by sshanzel**
## Changes
- The offset should be based on where the current line is at not the number of lines since it is only needed on lines after the first one.

This was reproducible locally and has been verified to work after the fix.

To reproduce, write multi-lined comments, for example:
```
Sample

Test
```

Then focus your cursor on the first line having it adjacent to the word `Sample`.

Should show the issue. After the code change, this doesn't happen anymore, and have verified commands on lines 2 onwards still work.

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-1734 #done

### CODE REVIEW

**Review by rebelchris — APPROVED** [review]
Oh wow, what a find!
Did you also get it locally to show way of screen?

I saw in Tsahi's exaple it was like in the top left corner.

**Comment by sshanzel** [comment]
> Did you also get it locally to show way of screen?

Was not able to reproduce the off-placement of the tooltip, but that should be relevant to the issue here as the placement is based on these calculations.

Have also deployed this in preview2 and it works as intended now.

**Comment by rebelchris** [comment]
@sshanzel Perfect, feel free to merge away 🙏
We can always ask in the ticket to verify on their side. (Maybe do this regardless :))

**Comment by sshanzel** [comment]
Verified on prod 🥳

**Pull request merged**
