### PR TITLE
fix: missing padding on checkbox

### PR DESCRIPTION
**Pull request by sshanzel**
DD-291 #done

In our design spec, our checkbox has `4px` padding = `0.25rem` and a right padding of `12px` = `0.75rem`.

Screen Shot 2021-11-10 at 10 30 17 AM

Affected existing implementations:

Screen Shot 2021-11-10 at 10 33 37 AM

Screen Shot 2021-11-10 at 10 34 22 AM

### CODE REVIEW

**Review by rebelchris — APPROVED** [review]
Looks good, however you might want to check some other implementations as well.
Like the report widget. I had to add a manual padding there, so that might now be offset.

From the top of my head, DnD might also have a special one.

If you check those, and they are valid, good to go from my side

**Review by idoshamun — APPROVED** [review]
I agree with @rebelchris. Please check for consistency and than you can merge

**Comment by sshanzel** [comment]
Totally correct, I will thoroughly check all existing implementations before merging. Thank you both for the comments! 🚀

**Comment by sshanzel** [comment]
After further checking, it seems everything got covered in the current commits. With that, I will proceed to merge. Thank you both! 🚀

**Pull request merged**
