### PR TITLE
fix: Your Website and Mastodon empty update not working

### PR DESCRIPTION
**Pull request by Abhi-Bohora**
## Changes
Linked Issue: (https://github.com/dailydotdev/daily/issues/1396)

### Describe what this PR does
In the`https://app.daily.dev/account/profile` in  `Profile Social Links` if the user tries to update the fields `Your Website` and `Mastodon` with empty values to remove their links then the old values would remain even after updating the value with empty values. So this PR aims to fix the issue so that users can remove profile links by setting empty values or update with valid values. other fields were working normally.

## Events

Did you introduce any new tracking events?

## Experiment

Did you introduce any new experiments?

## Manual Testing

> [!CAUTION]
> Please make sure existing components are not breaking/affected by this PR

### CODE REVIEW

**Review by sshanzel — COMMENTED** [review]
I think this goes the same to the other options such as twitter, gh, etc. - can you check if it actually is?

**Comment by Abhi-Bohora** [comment]
@sshanzel other field work as expected GitHub, twitter, etc these two fields only have a problem maybe due to a ternary condition set to undefined?

**Review by sshanzel — APPROVED** [review]
In that case, then yeah, this should fix the case 💪

**Review by sshanzel — COMMENTED** [review]
Sorry, one more thing I realized. We can maybe add a `type="url"` to those two inputs to ensure you either fill it or leave it blank.

**Comment by Abhi-Bohora** [comment]
@sshanzel, I just added `type="url"` to those input fields. sorry I didn't understand  if you want to keep this  `portfolio: values.portfolio ? withHttps(values.portfolio) : null` as `undefined`  same as before instead of `null`, if we keep it as `undefined` it didn't work it was same behaviour as before. so I kept it as `null`.

and one more thing I did git rebase because I cannot push changes it was giving me error maybe because there were many commits made already  let me know If this cause any problem. I don't know much about this. Thanks

**Review by rebelchris — APPROVED** [review]
Looks worth a try :) 
Perhaps we can try end 2 end on prod once merged?

**Review by sshanzel — APPROVED** [review]
Looks amazing! 🚀

**Comment by sshanzel** [comment]
@Abhi-Bohora tested in prod, worked as intended! 🥳

**Comment by sshanzel** [comment]
@Abhi-Bohora can you maybe link a social media profile of yours where I can send you some message?

**Pull request merged**
