### PR TITLE
fix: :bug: Fixed a bug in the most visited sites stack

### PR DESCRIPTION
**Pull request by rebelchris**
We where using a `gap-4` which caused all individual items in the most visited sites to space out.
I've decided to add separate margins to the dropdowns.

And add a items align so they are centered with the button.

Before:
image

After:
Screenshot 2022-01-17 at 15 34 43

DD-478 #done

### CODE REVIEW

**Review by sshanzel — COMMENTED** [review]
This looks like a great fix! Though I was thinking to fix it in the container of the `MostVisitedSites` component to make it predictable and avoid future glitches since it will have its own set of rules for its container.

What do you think of it?

**Comment by rebelchris** [comment]
It doesn't have a container at the moment.
But I think we can pick that up in the custom links task maybe?

**Comment by sshanzel** [comment]
Yes, I mean we will have to define an actual container for it instead of a fragment.

**Review by sshanzel — APPROVED** [review]
That makes sense, I'll look into it since it would at least take time to finish the custom links.

**Review by idoshamun — APPROVED** [review]
Great fix!

**Pull request merged**
