### PR TITLE
refactor: removal of unnecessary use effects for hiding scrollbar

### PR DESCRIPTION
**Pull request by sshanzel**
## Changes
- One reason why we are losing the scroll position is that we hide it from the user when we open the article modal.
- I noticed the Modal overlay was also not taking up the whole screen's width so it kinda shifts the whole UI when the background has its own scroll.
- Also fixed the overscroll behavior that should have solved the issue of stopping the scroll on the body when the modal is opened than having the previous hack of `overflow: hidden` which we removed here.

### Describe what this PR does
- Short and concise, bullet points can help
- Screenshots if applicable can also help

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

I believe the root cause of both these issues is the same. Hence, we will be able to close it once done.
WT-310 #done
WT-812 #done

### CODE REVIEW

**Comment by sshanzel** [comment]
@rebelchris can you try to open the preview deployment here and test it out? Though not now, please wait for the weekend to pass and enjoy it first 🏖️ 

@capJavert not sure if it happens to you too, but would appreciate additional tests 🙌 

Quick link: https://daily-webapp-isztu7zfv-dailydotdev.vercel.app/

**Comment by rebelchris** [comment]
> @rebelchris can you try to open the preview deployment here and test it out? Though not now, please wait for the weekend to pass and enjoy it first 🏖️ 
> 
> 
> 
> @capJavert not sure if it happens to you too, but would appreciate additional tests 🙌 
> 
> 
> 
> Quick link: https://daily-webapp-isztu7zfv-dailydotdev.vercel.app/

I just checked and it still happens on the provided preview on ios.

Scroll down a bit, open modal, deflects to top

**Comment by sshanzel** [comment]
> I just checked and it still happens on the provided preview on ios.
> 
> Scroll down a bit, open modal, deflects to top

I see, thanks for checking it out. I will see further what could be the cause.

**Comment by capJavert** [comment]
> @capJavert not sure if it happens to you too, but would appreciate additional tests 🙌
> 

Sorry, missed commenting on Friday, I see it still, same as Chris.

**Comment by sshanzel** [comment]
> Sorry, missed commenting on Friday, I see it still, same as Chris.

Thank you both 😭

**Comment by sshanzel** [comment]
@rebelchris @capJavert This was not able to fix the issue on iOS scroll but was able to at least delete two use effects. That in itself I think is a win already, so asking permission to merge but keep the tickets open.

**Comment by rebelchris** [comment]
@sshanzel This introduces a edge-case where modals now show the original's page scrollbar.
I'm afraid it might even introduce more edge-cases we simply haven't tested so would refrain merging for now.

Example of main page scrollbar:
Screenshot 2023-04-20 at 13 22 01

**Comment by rebelchris** [comment]
@sshanzel closing this one in favor of the implemented one.

**Comment by sshanzel** [comment]
I think we might still be able to reuse this, by reverting the fixes on the max-width of the modal which produced the scrollbar.

**Comment by sshanzel** [comment]
> @sshanzel This introduces a edge-case where modals now show the original's page scrollbar.

I checked our prod environment it seems to be the same having this scrollbar.

**Comment by sshanzel** [comment]
But I agree this must be held close until tested thoroughly. Let's just probably close this and create a ticket for improvement.

**Pull request closed without merging**
