### PR TITLE
fix: missing queryFn console error in useQuery usages

### PR DESCRIPTION
**Pull request by capJavert**
### Describe what this PR does

While trying to cleanup console clutter during development in #1573 I noticed another error that happens passively while clicking through the app `Error: Missing queryFn` coming from `useQuery` usages.

This happens in pattern when using useQuery as state hook. Valid fix should be to add queryFn that just loads up the current data of the query (if exists). I looked at the rest of the code and I can see that on some other places it is using the same pattern (eg. `packages/shared/src/components/notifications/Toast.tsx`) so I think these were just missed accidentally.

As far as I can see this does not break anything because all of the hooks fallback and handle when data is present or `undefined`.

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-{number} #done

### CODE REVIEW

**Comment by capJavert** [comment]
Not sure why the tests fail, I don't think it is connected to the changes here, noticed it also in #1573

**Review by rebelchris — APPROVED** [review]
Tested this and seems to work fine, I think we might have just missed these.
@sshanzel Do you know if this had any specific reason?

**Comment by sshanzel** [comment]
> Tested this and seems to work fine, I think we might have just missed these. @sshanzel Do you know if this had any specific reason?

I believe what Ante said is correct, in longer terms, we are trying to use `react-query` as a state to be accessed across the app in numerous areas. The implementation works as the only issue would be the initial state which is not a concern in those areas. Probably an anti-pattern but, yep, ensuring the function call is definitely safer by doing as what in this PR has displayed.

This is why I was suggesting the introduction of some state-management libraries like zustand/redux. The current implementations are a bit unpredictable.

**Comment by rebelchris** [comment]
@sshanzel I still think React query will work for now as state manager.
Maybe we should rather introduce some stricter linting.

But fully open to look at another state management solution in the meantime with future aspect in mind.
So thanks for bringing that to attention.

For time being how do you feel about this PR?

**Comment by sshanzel** [comment]
@rebelchris yep, I agree, current ones are just fine, probably when we get more complex requirements then we might actually need it.

Oh, sorry, I forgot to click the "Submit review" button 😅 
Everything looks amazing to me though! 🚢
Great work here @capJavert

**Review by sshanzel — APPROVED** [review]
Thanks for the cleanup! 🙏

**Comment by capJavert** [comment]
> > Tested this and seems to work fine, I think we might have just missed these. @sshanzel Do you know if this had any specific reason?
> 
> I believe what Ante said is correct, in longer terms, we are trying to use `react-query` as a state to be accessed across the app in numerous areas. The implementation works as the only issue would be the initial state which is not a concern in those areas. Probably an anti-pattern. Though I agree ensuring the function call is definitely safer by doing as what in this PR has displayed.
> 
> This is why in the past I was suggesting the introduction of some state-management libraries like zustand/redux. The current implementations are a bit unpredictable.

One additional thing that is maybe good to note when using `useQuery` as state manager.

The `query.stale` and `query.cache` options could be set to `Infinity`, this would mitigate any mismatches in data for empty query functions because those would never get invalidated and would behave more as true global state. 

Again this is not relevant for cases in this PR but in general.

**Comment by sshanzel** [comment]
> The query.stale and query.cache options could be set to Infinity, this would mitigate any mismatches in data for empty query functions because those would never get invalidated and would behave more as true global state.

Oh, that is good to know. Thank you for the tip!

**Pull request merged**
