### PR TITLE
fix: sidebar spacing between discover and squads

### PR DESCRIPTION
**Pull request by sshanzel**
### Describe what this PR does
- There was a missing spacing between the discover section and the list of squads

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-1071 #done

### CODE REVIEW

**Review by rebelchris — CHANGES_REQUESTED** [review]
Not sure this is the right fix Lee,
The issue only happens on the mobile menu, this fix seems to affect both right?

**Comment by sshanzel** [comment]
I am not yet aware of the issue on mobile, but the fix here should be on the desktop size which was discussed here:

https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1675951039937079

**Comment by sshanzel** [comment]
@rebelchris yes, this should fix both cases. On mobile and on desktop there was a missing margin.

image

image

**Comment by rebelchris** [comment]
The design is only mobile ;)
It should not change the desktop size as far as I can tell. that was already good.

**Comment by sshanzel** [comment]
> The design is only mobile ;) It should not change the desktop size as far as I can tell. that was already good.

Oh, from the design here, there seems to be a margin in-between.

image

**Review by rebelchris — APPROVED** [review]
Hmm seems changed since last viewed, so good to go.

**Comment by sshanzel** [comment]
> Hmm seems changed since last viewed, so good to go.

Let me confirm with the design team just to be 101% sure. This can probably be for introducing custom feeds in the future, but they can better answer it. I will get back to this.

**Comment by sshanzel** [comment]
@rebelchris confirmed! it seems they have made a recent change to the spacing.

**Pull request merged**
