### PR TITLE
fix: read it later on collections card

### PR DESCRIPTION
**Pull request by sshanzel**
## Changes
- Fix the freeform footer component by using our common `CardCover` component.

Preview:

Screenshot 2024-08-05 at 10 45 04 PM

## Events

Did you introduce any new tracking events?

## Experiment

Did you introduce any new experiments?

## Manual Testing

> [!CAUTION]
> Please make sure existing components are not breaking/affected by this PR

### Preview domain
https://fix-collections.preview.app.daily.dev

### CODE REVIEW

**Comment by nensidosari** [comment]
@sshanzel 
Screenshot 2024-08-05 at 5 33 44 PM
there is an issue with some of the images now with the change on collection cards

**Comment by nensidosari** [comment]
@sshanzel please also check list mode of these cards, is not working there as well

**Comment by nensidosari** [comment]
@sshanzel still click over the image on list mode takes precedence over the reminder buttons

**Comment by sshanzel** [comment]
> @sshanzel still click over the image on list mode takes precedence over the reminder buttons

Yeah, I am working on it.

**Comment by sshanzel** [comment]
@nensidosari should be working as intended now.

https://fix-collections.preview.app.daily.dev/sources/collections

**Comment by sshanzel** [comment]
This also fixes the the upvote on collection cards to not showing the share loops.

**Comment by sshanzel** [comment]
@nensidosari feel free to review when you get some free time. Thank you!

**Comment by nensidosari** [comment]
@sshanzel from my last checks I have few more things concerning:

- the freeform post still doesn't work on list mode
- on list mode when clicking on the bookmark/reminder icon (so after the post is bookmarked) the menu doesn't show up
- on list mode when bookmarking/removing bookmark or adding reading reminder, the image flashes, it doesn't do this in cards.


https://github.com/user-attachments/assets/949f7d15-31d9-4c5a-a97a-3115587deac3

https://github.com/user-attachments/assets/7f3f225c-d6c4-46cc-8f33-7d2c9ef8ebf9

**Comment by sshanzel** [comment]
> on list mode when clicking on the bookmark/reminder icon (so after the post is bookmarked) the menu doesn't show up

They seem to open from my end. On the recording, you seem to have not clicked the button.

> - the freeform post still doesn't work on list mode
> - on list mode when bookmarking/removing bookmark or adding reading reminder, the image flashes, it doesn't do this in cards.

These two should have been fixed by now.

With regards to the state when there is no image on both card and list layout, let's maybe do it in a separate PR as we are still waiting for the design on the list layout.

**Comment by nensidosari** [comment]
> on list mode when clicking on the bookmark/reminder icon (so after the post is bookmarked) the menu doesn't show up

They seem to open from my end. On the recording, you seem to have not clicked the button.

@sshanzel seems to happen still on my end, tried in incognito as well. I have clicked the button. Anyways this seems like a separate issue so let's treat it separately 🙌

**Review by nensidosari — APPROVED** [review]
Thank u for bearing with my testings.

**Comment by sshanzel** [comment]
> Thank u for bearing with my testings.

I should actually thank you for that 😅 

Should now be working as intended.

**Review by nensidosari — APPROVED** [review]

**Pull request merged**
