### PR TITLE
fix: show header login buttons if not logged in

### PR DESCRIPTION
**Pull request by omBratteng**
## Changes

Adds the missing login and signup button in the header

<table>
<tr>
<td>Before
<td>After
<tr>
<td>
<td>
</table>

### Preview domain
https://fix-login-button-in-header.preview.app.daily.dev

### CODE REVIEW

**Comment by rebelchris** [comment]
Not 100% sure but was it maybe intentional in favor of the big CTA at the bottom?
Screenshot 2024-06-05 at 09 18 16

@nensidosari you might know?

**Comment by sshanzel** [comment]
> Not 100% sure but was it maybe intentional in favor of the big CTA at the bottom?

I vaguely remember, but I believe it should still be there on tablet. Just need to make sure it is not there on mobile.

**Comment by omBratteng** [comment]
@rebelchris I think it got accidentally removed in #2829. And right now the banner doesn't exist on public pages like squads, sources and
<table>
<tr>
<td>
<td>
<tr>
<td>
<td>
</table>

**Comment by omBratteng** [comment]
Also having it in header _and_ banner (where applicable) doesn't hurt.

**Review by rebelchris — APPROVED** [review]

**Comment by omBratteng** [comment]
> seems I'm breaking code a lot lol

That's not your job?

**Pull request merged**
