### PR TITLE
fix: sidebar title z-index

### PR DESCRIPTION
**Pull request by sshanzel**
### Describe what this PR does
- Ido mentioned this was a known issue before, I'm not sure what was the fix before but if you do remember, kindly drop in the comments. Thank you! @rebelchris 

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-1013 #done

### CODE REVIEW

**Review by rebelchris — CHANGES_REQUESTED** [review]
I think it has more to do with the render boolean wether something should be visible on mobile or not.
Perhaps look at the ones that do show and see which props we pass to those?

**Review by el — APPROVED** [review]
LGTM :shipit:

**Comment by sshanzel** [comment]
@rebelchris for better devex, I have labeled the prop differently to be more straightforward and have it checked directly from the `Sidebar` so when used, we won't have to always remember to use two variables.

**Review by rebelchris — APPROVED** [review]
Looks good, Ido mentioned it's already working, but this makes it more readable anyway so well done 👍

**Pull request merged**
