### PR TITLE
fix: typo in CI config

### PR DESCRIPTION
**Pull request by DragosIorgulescu**
## Changes

just a typo

## Events

N / A

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-{number} #done

### CODE REVIEW

**Review by omBratteng — DISMISSED** [review]
toasty-the-walking-toast

**Review by omBratteng — APPROVED** [review]
toasty-the-walking-toast

**Review by capJavert — APPROVED** [review]
@denisb0 approves!

**Comment by idoshamun** [comment]
Not gonna happen!!!!

**Comment by omBratteng** [comment]
> Not gonna happen!!!!

I do not approve.

**Pull request closed without merging**
