### PR TITLE
feat: slack private channels

### PR DESCRIPTION
**Pull request by capJavert**
## Changes

Additional permissions for slack oauth to be able to access private channels.

API https://github.com/dailydotdev/daily-api/pull/2141

## Events

Did you introduce any new tracking events?

## Experiment

Did you introduce any new experiments?

## Manual Testing

> [!CAUTION]
> Please make sure existing components are not breaking/affected by this PR

AS-521 #done

### Preview domain
https://as-521-slack-private-channels.preview.app.daily.dev

### CODE REVIEW

**Review by omBratteng — APPROVED** [review]

**Comment by omBratteng** [comment]
Tested connecting, as it's now asking for private channels
image

Waiting for API to be deployed, to see if it actually can list them out

**Comment by omBratteng** [comment]
I reconnected, but can still only see public channels?
image

**Comment by omBratteng** [comment]
Nvm, I just forgot to RTFM

**Comment by omBratteng** [comment]
Don't know if it's in scope, but it would be nice to see a lock instead of a # next to private channels, like Slack does in their GUI

**Comment by capJavert** [comment]
Not for now, but revamp of dropdown is up there so could be then.

**Pull request merged**
