### PR TITLE
fix: mobile pills

### PR DESCRIPTION
**Pull request by rebelchris**
### Describe what this PR does
- Had to manipulate buttons as it's not technically in our button design system.

Screenshot 2023-08-29 at 10 20 01

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-{number} #done

### CODE REVIEW

**Comment by omBratteng** [comment]
Is there a reason why the icon is padded differently?
image

**Comment by rebelchris** [comment]
@omBratteng Good spot, shouldn't be the case 👀
I'll go back to see what's up

**Review by sshanzel — APPROVED** [review]
Looks good! 🚀

**Comment by rebelchris** [comment]
@omBratteng Updated screenshot and fixed.
Let me know if that works 🙏

**Comment by omBratteng** [comment]
Looks better now with them aligned correctly. Though I do feel a bit cramped between the icon and the text. Is it possible to increase the margin between the icon and text by a few pixels?

**Comment by rebelchris** [comment]
@omBratteng That's according to spec, so will leave for now.
We have a upcoming task soon to deal with button cleanup

**Pull request merged**
