### PR TITLE
feat: removing the bg color from the similar posts sidebar widget

### PR DESCRIPTION
**Pull request by TomDowling**
## Changes
Removing the bg-color set on the similar posts widget so it matches the rest of the widgets in the sidebar

### Describe what this PR does
- Short and concise, bullet points can help
- Screenshots if applicable can also help

## Events

Did you introduce any new tracking events?
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0)

Log the new/changed events below:

| Type   | event_name  | value |
|--------|-------------|-------|
| Change/New | event name  | extra: { ... } |

### On those affected packages:
- [ ] Have you done sanity checks in the webapp?
- [ ] Have you done sanity checks in the extension?
- [ ] Does this not break anything in companion?

### Did you test the modified components media queries?
- [ ] MobileL (420px)
- [ ] Tablet (656px)
- [ ] Laptop (1020px)

#### Did you test on actual mobile devices?
- [ ] iOS (Chrome and Safari)
- [ ] Android

WT-1461 #done

### CODE REVIEW

**Review by rebelchris — APPROVED** [review]
Awesome 👍

**Comment by sshanzel** [comment]
Should we maybe do this on the ToC too?

Screenshot 2023-06-26 at 4 48 00 PM

**Comment by rebelchris** [comment]
@TomDowling / @sshanzel The TOC is another ticket [seperated](https://dailydotdev.atlassian.net/jira/software/projects/WT/boards/11/backlog?selectedIssue=WT-1476&text=background) logged.

**Comment by TomDowling** [comment]
@sshanzel @rebelchris, Another PR has that ToC fixed as well :)
https://github.com/dailydotdev/apps/pull/1907

**Pull request merged**
