### PR TITLE
Fix: "Start the discussion" bar on the article page is partially hidden in mobile Safari #300

### PR DESCRIPTION
**Pull request by miralsuthar**

### CODE REVIEW

**Review by idoshamun — CHANGES_REQUESTED** [review]
Thanks for the contribution but the idea here was to provide a fix just for the mobile safari use case rather than changing for every device.
You can see here an example of how to achieve it:
https://github.com/dailydotdev/apps/pull/587/files#diff-633d399853a31a27ddc752b1e5dffefc37fe822f179be40c675bd1a2d708885cR4
Look at the highlighted line.

**Comment by miralsuthar** [comment]
Hey, @idoshamun I have change the code as you requested that style should only change for mobile safari.

Have a look at it 😄

**Comment by idoshamun** [comment]
I will! I'm going on vacation for a few days might be less available. Please make sure sign the CLA above

**Comment by idoshamun** [comment]
Please also run `npm run lint -- --fix` to fix the lint issue

**Comment by miralsuthar** [comment]
hey, @idoshamun I think there is some issue with the commit from my side for that CLA license so I am closing this PR and opening new.

**Pull request closed without merging**
